# Generated by Django 3.2.2 on 2021-05-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=13)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='홍길동', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.departments'),
        ),
    ]
